#!/usr/bin/env bash

pushd $(cd -P -- "$(dirname -- "$0")" && pwd -P)/..

docker-compose -f docker-compose.test.yml build

docker-compose -f docker-compose.test.yml up -d

docker logs -f docker_sut_1

RET=`docker wait docker_sut_1`

popd

exit $RET
