#!/bin/bash

[ -z ${NAME-} ] && exit 1
[ -z ${NPM_TOKEN-} ] && exit 1

VERSION=$(if [ -z ${VERSION-} ]; then echo latest; else echo $VERSION; fi)
VERSION_COMMIT=$(if [ -z ${VERSION_COMMIT-} ]; then echo `$(which git) rev-parse --short HEAD`; else echo $VERSION_COMMIT; fi)
VERSION_BUILD_DATE=$(which date)

IMAGE_NAME=$(if [ -z ${IMAGE_NAME-} ]; then echo hfreire/$NAME:$VERSION; else echo $IMAGE_NAME; fi)

$(which docker) build -t ${IMAGE_NAME} -f ../Dockerfile \
--build-arg=NPM_TOKEN=${NPM_TOKEN} \
--build-arg=NAME=${NAME} \
--build-arg=VERSION=${VERSION} \
--build-arg=VERSION_COMMIT=${VERSION_COMMIT} \
--build-arg=VERSION_BUILD_DATE=\"${VERSION_BUILD_DATE}\" \
../../..
